version: '3'
services:
  app:

    image: securitealimentaire:latest
    container_name: my-app
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - web

networks:
  web:
    driver: bridge
