version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173"  # Mappe le port 5173 du conteneur au port 3000 de l'hôte

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Expose le port 80
    depends_on:
      - app
